# Указываем версию docker-compose файла
version: "3"

# docker-compose работает с сервисами 
# 1 сервис = 1 контейнер 
# Сервисом может быть клиент, сервер, сервер баз данных 
# Раздел, в котором будут описаны сервисы, начинается с "services"

services:
  
  # Нам нужно два сервиса 
  # Первый сервис(контейнер): сервер нашего приложения
  # Называть лучше так, как будет наибелее интуитивно понятно разработчику. Чтобы понятна была его роль
  server:
    # Ключевое слово build позволяет задать путь к Dockerfile, который нужно использовать для создания образа(который позволит запустить сервис)
    # Здесь server/ соответствует пути к папке сервера
    build: server/
    # Команда, которую нужно запустить после создания образа
    command: python ./server.py
    # Нам нужно использовать порт хоста 1234 и организовать его связь с портом 1234 контейнера(так как на этот порт сервер ожидает запроса)
    ports:
      - 1234:1234
    
    # Второй сервис - клиент 
  client:
    build: client/
    command: python ./client.py
    # Ключевое слово "network_mode" используем для описания типа сети.
    # Указываем что контейнер может обращатся к localhost компьютера 
    network_mode: host
    # depends_on - указываем что сервис перед запуском должен дождаться пока будет "готов" сервис 'server'
    depends_on:
      - server
